#!/bin/bash
#
# WHID Installer — run this once, then use 'whid' from anywhere.
#
# Usage:
#   git clone https://github.com/matjes993/WhatHaveIDone.git
#   ./WhatHaveIDone/install.sh
#

set -e

# Find project root (where this script lives)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$SCRIPT_DIR/venv"
BIN_DIR="$HOME/.local/bin"
WHID_BIN="$BIN_DIR/whid"

echo ""
echo "=================================="
echo "  Installing WhatHaveIDone (WHID)"
echo "=================================="
echo ""

# Check Python
if command -v python3 &>/dev/null; then
    PYTHON=python3
elif command -v python &>/dev/null; then
    PYTHON=python
else
    echo "Error: Python 3.9+ is required but not found."
    echo ""
    echo "Install Python:"
    case "$(uname -s)" in
        Darwin) echo "  brew install python3" ;;
        Linux)  echo "  sudo apt install python3 python3-venv" ;;
        *)      echo "  Download from https://python.org" ;;
    esac
    exit 1
fi

# Check Python version
PY_VERSION=$($PYTHON -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$($PYTHON -c "import sys; print(sys.version_info.major)")
PY_MINOR=$($PYTHON -c "import sys; print(sys.version_info.minor)")

if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 9 ]; }; then
    echo "Error: Python 3.9+ required, found $PY_VERSION"
    exit 1
fi

echo "Using Python $PY_VERSION"

# Create virtual environment
if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment..."
    $PYTHON -m venv "$VENV_DIR"
fi

# Install dependencies
echo "Installing dependencies..."
"$VENV_DIR/bin/pip" install -q -e "$SCRIPT_DIR"

# Create bin directory
mkdir -p "$BIN_DIR"

# Create global 'whid' command
cat > "$WHID_BIN" << WRAPPER
#!/bin/bash
# WHID launcher — auto-generated by install.sh
exec "$VENV_DIR/bin/python" "$SCRIPT_DIR/whid.py" "\$@"
WRAPPER
chmod +x "$WHID_BIN"

echo ""

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    # Detect shell config file
    SHELL_NAME="$(basename "$SHELL")"
    case "$SHELL_NAME" in
        zsh)  RC_FILE="$HOME/.zshrc" ;;
        bash) RC_FILE="$HOME/.bashrc" ;;
        *)    RC_FILE="$HOME/.profile" ;;
    esac

    # Add to PATH
    echo "" >> "$RC_FILE"
    echo '# WHID (WhatHaveIDone)' >> "$RC_FILE"
    echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$RC_FILE"

    echo "Added $BIN_DIR to PATH in $RC_FILE"
    echo ""
    echo "=================================="
    echo "  Install complete!"
    echo "=================================="
    echo ""
    echo "  Run this to start using whid now:"
    echo ""
    echo "    source $RC_FILE"
    echo "    whid setup gmail"
    echo ""
else
    echo "=================================="
    echo "  Install complete!"
    echo "=================================="
    echo ""
    echo "  Run:  whid setup gmail"
    echo ""
fi
